apiVersion: v1
kind: Service
metadata:
  name: personal-crm
  namespace: personal-crm
spec:
  type: ClusterIP
  selector:
    app: personal-crm
  ports:
    - name: http
      port: 3000
      targetPort: http
